
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class City

    Public Property CityId As Integer

    Public Property CityName As String



    Public Overridable Property Suburbs As ICollection(Of Suburb) = New HashSet(Of Suburb)


End Class
