
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class EmailTemplate

    Public Property EmailTemplateId As Integer

    Public Property UserId As String

    Public Property TimeStamp As Date

    Public Property EmailTemplateName As String

    Public Property IsDefault As Nullable(Of Boolean)


End Class
