
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class EmailTemplateDetail

    Public Property EmailTemplateDetailsId As Integer

    Public Property EmailTemplateDetailsName As String

    Public Property EmailTemplateDetailsContent As String

    Public Property EmailTypeId As Integer

    Public Property EmailTemplateId As Nullable(Of Integer)



    Public Overridable Property EmailType As EmailType


End Class
