
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class EmailType

    Public Property EmailTypeId As Integer

    Public Property EmailType1 As String



    Public Overridable Property EmailTemplateDetails As ICollection(Of EmailTemplateDetail) = New HashSet(Of EmailTemplateDetail)


End Class
