
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class EmailQueue

    Public Property QueueId As Integer

    Public Property QueueDate As Date

    Public Property VCVId As Integer

    Public Property EmailTo As String

    Public Property EmailFrom As String

    Public Property IsProcessed As Boolean

    Public Property ProcessedDate As Nullable(Of Date)


End Class
