
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class ListingApplication

    Public Property ApplicationId As Integer

    Public Property UserId As String

    Public Property ListingId As Integer

    Public Property VideoName As String

    Public Property Attachment1Id As String

    Public Property Attachment1Name As String

    Public Property Attachment2Id As String

    Public Property Attachment2Name As String

    Public Property Attachment3Id As String

    Public Property Attachment3Name As String

    Public Property TimeStamp As Date

    Public Property SummaryContent As String

    Public Property IsShortlist As Boolean

    Public Property IsDeclined As Boolean

    Public Property IsViewed As Boolean

    Public Property ApplicationStatusId As Integer



    Public Overridable Property Listing As Listing

    Public Overridable Property User As User

    Public Overridable Property ApplicationStatu As ApplicationStatus


End Class
