
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Listing

    Public Property ListingId As Integer

    Public Property ListingTitle As String

    Public Property Company As String

    Public Property SubCategoryId As Integer

    Public Property ListingTypeId As Integer

    Public Property ListingPayId As Integer

    Public Property ListingReference As String

    Public Property ListingSummary As String

    Public Property ListingDescription As String

    Public Property IsAdvertised As Boolean

    Public Property UserId As String

    Public Property SuburbId As Integer

    Public Property Image1 As String

    Public Property Image2 As String

    Public Property Image3 As String

    Public Property EmailNotificationsEnabled As Boolean

    Public Property EmailTemplateId As Nullable(Of Integer)

    Public Property PublicId As String

    Public Property Completed As Nullable(Of Boolean)

    Public Property Fulfilled As Nullable(Of Boolean)

    Public Property ListedDate As Nullable(Of Date)

    Public Property ExpiryDate As Nullable(Of Date)



    Public Overridable Property ListingPay As ListingPay

    Public Overridable Property ListingType As ListingType

    Public Overridable Property SubCategory As SubCategory

    Public Overridable Property Suburb As Suburb

    Public Overridable Property WatchLists As ICollection(Of WatchList) = New HashSet(Of WatchList)

    Public Overridable Property ListingApplications As ICollection(Of ListingApplication) = New HashSet(Of ListingApplication)


End Class
