
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class SubCategory

    Public Property SubCategoryId As Integer

    Public Property SubCategoryName As String

    Public Property CategoryId As Integer



    Public Overridable Property Category As Category

    Public Overridable Property Listings As ICollection(Of Listing) = New HashSet(Of Listing)


End Class
