
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Tran

    Public Property TranId As Integer

    Public Property TranType As String

    Public Property TranAmount As Decimal

    Public Property UserId As String

    Public Property Completed As Boolean

    Public Property TimeStamp As Nullable(Of Date)



    Public Overridable Property User As User


End Class
