
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class User

    Public Property UserId As String

    Public Property UserName As String

    Public Property UserPassword As String

    Public Property UserType As String

    Public Property Activated As Nullable(Of Boolean)

    Public Property Completed As Nullable(Of Boolean)

    Public Property PurchaseDate As Nullable(Of Date)

    Public Property LastBillingDate As Nullable(Of Date)

    Public Property NextBillingDate As Nullable(Of Date)

    Public Property RecurringBillingId As String

    Public Property UserEmail As String

    Public Property Terms As Boolean

    Public Property ForgotToken As String

    Public Property ForgotDateLimit As Nullable(Of Date)

    Public Property Removed As Boolean

    Public Property CountryId As Nullable(Of Integer)



    Public Overridable Property VCVs As ICollection(Of VCV) = New HashSet(Of VCV)

    Public Overridable Property Scripts As ICollection(Of Script) = New HashSet(Of Script)

    Public Overridable Property Summaries As ICollection(Of Summary) = New HashSet(Of Summary)

    Public Overridable Property Trans As ICollection(Of Tran) = New HashSet(Of Tran)

    Public Overridable Property WatchLists As ICollection(Of WatchList) = New HashSet(Of WatchList)

    Public Overridable Property ListingApplications As ICollection(Of ListingApplication) = New HashSet(Of ListingApplication)

    Public Overridable Property Country As Country

    Public Overridable Property VCVShareds As ICollection(Of VCVShared) = New HashSet(Of VCVShared)


End Class
