

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure



Partial Public Class VCVOnlineEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=VCVOnlineEntities")

    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Property Users() As DbSet(Of User)

    Public Property VCVs() As DbSet(Of VCV)

    Public Property Countries() As DbSet(Of Country)

    Public Property Scripts() As DbSet(Of Script)

    Public Property Summaries() As DbSet(Of Summary)

    Public Property Trans() As DbSet(Of Tran)

    Public Property EmailQueues() As DbSet(Of EmailQueue)

    Public Property Templates() As DbSet(Of Template)

    Public Property EmailSignups() As DbSet(Of EmailSignup)

    Public Property Cities() As DbSet(Of City)

    Public Property ListingPays() As DbSet(Of ListingPay)

    Public Property ListingTypes() As DbSet(Of ListingType)

    Public Property Suburbs() As DbSet(Of Suburb)

    Public Property Categories() As DbSet(Of Category)

    Public Property SubCategories() As DbSet(Of SubCategory)

    Public Property Listings() As DbSet(Of Listing)

    Public Property WatchLists() As DbSet(Of WatchList)

    Public Property ListingApplications() As DbSet(Of ListingApplication)

    Public Property ApplicationStatus1() As DbSet(Of ApplicationStatus)

    Public Property EmailTemplates() As DbSet(Of EmailTemplate)

    Public Property EmailTypes() As DbSet(Of EmailType)

    Public Property Products() As DbSet(Of Product)

    Public Property EmailTemplateDetails() As DbSet(Of EmailTemplateDetail)

    Public Property VCVShareds() As DbSet(Of VCVShared)


End Class

