
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VCV

    Public Property VCVId As Integer

    Public Property UserId As String

    Public Property VCVName As String

    Public Property Timestamp As Nullable(Of Date)

    Public Property VideoName As String

    Public Property ScriptId As Nullable(Of Integer)

    Public Property Attachment1Id As String

    Public Property Attachment1Name As String

    Public Property Attachment2Id As String

    Public Property Attachment2Name As String

    Public Property Attachment3Id As String

    Public Property Attachment3Name As String

    Public Property SummaryId As Nullable(Of Integer)

    Public Property CurrentStep As Integer

    Public Property Approved As Nullable(Of Boolean)

    Public Property DeclineReason As String

    Public Property Hidden As Boolean

    Public Property Token As String

    Public Property TokenExpiryDate As Nullable(Of Date)

    Public Property Length As String



    Public Overridable Property Script As Script

    Public Overridable Property Summary As Summary

    Public Overridable Property UserByVCV As User


End Class
