
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class WatchList

    Public Property WatchListId As Integer

    Public Property ListingId As Integer

    Public Property Timestamp As Date

    Public Property Status As Boolean

    Public Property UserId As String



    Public Overridable Property Listing As Listing

    Public Overridable Property User As User


End Class
